### ISSUE TITLE
Need to implement more API

### ISSUE THREAD

**Issue by vinodkumartheking** [pesto-students/deep-dive-soumsps#16]
We should plan to add more api to our modal like the following,

- scrollContent,
- toolTip,
- accessibility

**Comment by soumsps** [comment]
Hey, @vinodkumartheking following are inputs from my side. 

**scrollContent:** I am assuming that we are here talking about background content scroll lock. I feel its a _must-have_ and _must be enabled_ always kind of feature from modal dialog perspective. So, giving user an API to override will defeat its purpose.

**toolTip:** In my opinion, we already have labels, placeholder text, and ARIA labels for input fields. So, do we really need more things 😜

**accessibility:** I think this is again  _must-have_ and _must be enabled_ always kind of feature from modal dialog perspective.

Let me know your views on the above-mentioned points. 😊

**Comment by soumsps** [comment]
Closing this issue now, feel free to re-open it for discussion.
